"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY signs sessions and password-reset tokens. A known or guessable
# value means anyone can forge a password-reset link for any account, so in
# production a missing or placeholder key is a hard failure rather than a
# silent fallback.
_INSECURE_DEFAULT_SECRET_KEY = 'django-insecure-your-secret-key-here'
# `or` rather than a getenv default so an env var set to an empty string is
# treated as missing instead of silently becoming an empty signing key.
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY') or _INSECURE_DEFAULT_SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
# For PythonAnywhere, set DEBUG=False by default
DEBUG = os.getenv('DEBUG', 'False') == 'True'

if not DEBUG:
    if SECRET_KEY == _INSECURE_DEFAULT_SECRET_KEY:
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY is not set. Refusing to start with the public "
            "placeholder key in production — it would let anyone forge password "
            "reset links. Generate one with:\n"
            "  python -c \"from django.core.management.utils import "
            "get_random_secret_key; print(get_random_secret_key())\"\n"
            "then add it to .env as DJANGO_SECRET_KEY."
        )
    if SECRET_KEY.startswith('django-insecure-'):
        print(
            "WARNING: DJANGO_SECRET_KEY still looks like a development key "
            "('django-insecure-...'). Replace it with a freshly generated one."
        )

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',    
    '172.20.10.3',
    '172.20.10.3', 
    '.onrender.com',  # Render deployment
    '.pythonanywhere.com',  # PythonAnywhere deployment
    # Add your custom domain here when you have one
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'csp',  # Content Security Policy
    # 'cloudinary_storage',  # Cloudinary storage backend - commented out for local storage
    
    # Local apps
    'users',
    'products',
    'apps.payments',
    'apps.notifications',
    'apps.events',
    'apps.support',
    
    # Celery apps
    'django_celery_beat',
    'django_celery_results',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Recover the real visitor IP from the frontend proxy BEFORE anything reads
    # it, so per-IP rate limits apply per visitor and not to the shared proxy IP.
    'core.middleware.RealClientIPMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add WhiteNoise for static files
    'csp.middleware.CSPMiddleware',  # Content Security Policy
    'core.middleware.CustomSecurityMiddleware',  # Custom security headers
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database configuration with connection pooling
if os.getenv('DATABASE_URL'):
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.parse(os.getenv('DATABASE_URL'))
    }
    # Add connection pooling for production
    DATABASES['default']['CONN_MAX_AGE'] = 60
    DATABASES['default']['OPTIONS'] = {
        'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        'charset': 'utf8mb4',
    }
elif os.getenv('MYSQL_DATABASE'):
    # MySQL configuration for development/production
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('MYSQL_DATABASE', 'darra_app'),
            'USER': os.getenv('MYSQL_USER', 'darra_user'),
            'PASSWORD': os.getenv('MYSQL_PASSWORD', 'password'),
            'HOST': os.getenv('MYSQL_HOST', 'localhost'),
            'PORT': os.getenv('MYSQL_PORT', '3306'),
            'CONN_MAX_AGE': 60,  # Connection pooling
            'OPTIONS': {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
                'charset': 'utf8mb4',
            },
        }
    }
else:
    # SQLite for local development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# WhiteNoise configuration for static files
# Use WhiteNoise for static files serving
STATICFILES_STORAGE = 'whitenoise.storage.StaticFilesStorage'

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Private media — paid product files (ebooks, audio) live OUTSIDE MEDIA_ROOT so
# the web server never serves them directly. They are only streamed to buyers
# through the authenticated download endpoint after purchase. Cover images stay
# in MEDIA_ROOT because they are meant to be public.
PRIVATE_MEDIA_ROOT = os.path.join(BASE_DIR, 'private_media')

# Cloudflare R2 (S3-compatible) for paid product files. Set all four to move
# those files off the server disk; leave any blank and they stay on local disk
# under PRIVATE_MEDIA_ROOT. Nothing else is affected — cover images, banners
# and ticket QR codes always stay local (they are tiny). See
# products.models.private_product_storage.
R2_ACCESS_KEY_ID = os.getenv('R2_ACCESS_KEY_ID', '')
R2_SECRET_ACCESS_KEY = os.getenv('R2_SECRET_ACCESS_KEY', '')
R2_BUCKET_NAME = os.getenv('R2_BUCKET_NAME', '')
# e.g. https://<account-id>.r2.cloudflarestorage.com
R2_ENDPOINT_URL = os.getenv('R2_ENDPOINT_URL', '')

# Local file storage configuration
# No additional configuration needed - Django will use local storage by default

# Production media file serving
if not DEBUG:
    # In production, we need to serve media files through the web server
    # This is handled by the URL configuration in urls.py
    pass

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'users.User'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # Rate Limiting Configuration
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',      # Anonymous users
        'rest_framework.throttling.UserRateThrottle',      # Authenticated users
        'rest_framework.throttling.ScopedRateThrottle',    # Custom scoped throttling
    ],
    'DEFAULT_THROTTLE_RATES': {
        # Per anonymous visitor (real IP, recovered by RealClientIPMiddleware).
        # Generous because one person casually browsing fires many reads; still
        # low enough to slow a scraper coming from a single address.
        'anon': '500/hour',
        'user': '1000/hour',       # 1000 requests per hour for authenticated users
        'burst': '60/minute',      # 60 requests per minute (burst protection)
        'sustained': '1000/hour',  # 1000 requests per hour (sustained usage)
        'payment': '30/minute',    # 30 payment requests per minute
        'auth': '10/minute',       # 10 authentication attempts per minute
        'webhook': '100/minute',   # 100 webhook calls per minute
        # The chat endpoint spends money on every call, so it is throttled
        # harder than anything else — an unthrottled AI proxy is somebody
        # else's free API key.
        'support_chat': '15/minute',
        'contact': '5/hour',       # human-handoff / contact form submissions
    },
}

# JWT settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

# CORS settings
if DEBUG:
    # Development: Allow all origins for local development
    CORS_ALLOW_ALL_ORIGINS = True
    print("CORS: Development mode - allowing all origins")
else:
    # Production: Only allow specific trusted domains
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = [
        "https://darra-app.com",           # Replace with your actual domain
        "https://app.darra-app.com",       # Replace with your app domain
        "https://www.darra-app.com",       # Replace with your www domain
        "https://your-mobile-app.com",     # Your mobile app domain if any
    ]
    print("CORS: Production mode - restricted origins")

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Email settings
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')

# Check if email credentials are configured
if not DEBUG and EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_USE_SSL = False
    DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
    print("Email: Production mode - SMTP configured")
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    print("Email: Development mode - console backend")

# Paystack settings
PAYSTACK_SECRET_KEY = os.getenv('PAYSTACK_SECRET_KEY', 'sk_test_your_test_secret_key_here')
PAYSTACK_PUBLIC_KEY = os.getenv('PAYSTACK_PUBLIC_KEY', 'pk_test_your_test_public_key_here')

# Flutterwave settings
FLUTTERWAVE_SECRET_KEY = os.getenv('FLUTTERWAVE_SECRET_KEY', 'FLWSECK_TEST_your_test_secret_key_here')
FLUTTERWAVE_PUBLIC_KEY = os.getenv('FLUTTERWAVE_PUBLIC_KEY', 'FLWPUBK_TEST_your_test_public_key_here')
FLUTTERWAVE_ENCRYPTION_KEY = os.getenv('FLUTTERWAVE_ENCRYPTION_KEY', 'FLWSECK_TEST_your_test_encryption_key_here')
# The "Secret hash" you set on the Flutterwave dashboard webhook page.
# Flutterwave sends it back in the verif-hash header so we can prove a webhook
# actually came from them. Without it, webhooks are rejected.
FLUTTERWAVE_SECRET_HASH = os.getenv('FLUTTERWAVE_SECRET_HASH', '')

# Payment provider selection (can be 'paystack' or 'flutterwave')
PAYMENT_PROVIDER = os.getenv('PAYMENT_PROVIDER', 'paystack')
BASE_URL = os.getenv('BASE_URL', 'http://localhost:8000')

# Public site address used for links inside emails (receipts, sale alerts).
# This is the FRONTEND, not the API — set FRONTEND_URL in .env per environment.
# The fallback is deliberately environment-aware: defaulting to localhost in
# production would send buyers a dead link in every receipt, and nothing would
# error to tell us about it.
_DEFAULT_FRONTEND_URL = 'http://localhost:3000' if DEBUG else 'https://darra.com.ng'
FRONTEND_URL = os.getenv('FRONTEND_URL', _DEFAULT_FRONTEND_URL).rstrip('/')

if not DEBUG and not os.getenv('FRONTEND_URL'):
    print(
        f"WARNING: FRONTEND_URL is not set; email links will use "
        f"{_DEFAULT_FRONTEND_URL}. Set it in .env to be explicit."
    )

# Support chat AI.
# Provider-neutral names on purpose: Groq (api.groq.com, keys start 'gsk_') and
# xAI Grok (api.x.ai, keys start 'xai-') are different companies with similar
# names, and both speak the OpenAI chat-completions format. Swapping provider
# is a change of URL, model and key — no code change.
#
# The key stays on the server and never reaches the browser: the frontend talks
# to our own endpoint, which forwards upstream. Shipping it to the client would
# let anyone spend your credits.
SUPPORT_AI_API_KEY = os.getenv('SUPPORT_AI_API_KEY', '')
SUPPORT_AI_API_URL = os.getenv(
    'SUPPORT_AI_API_URL', 'https://api.groq.com/openai/v1/chat/completions'
)
SUPPORT_AI_MODEL = os.getenv('SUPPORT_AI_MODEL', 'llama-3.3-70b-versatile')

# Who receives operational alerts (e.g. "a seller requested a payout").
# Deliberately optional: leave it unset and alerts go to every active
# superuser in the database, so adding or removing an admin in Django admin is
# enough — no config change, no redeploy, and no address to go stale. Set it
# only when you want alerts sent somewhere that isn't an admin account.
ADMIN_ALERT_EMAILS = [
    e.strip() for e in os.getenv('ADMIN_ALERT_EMAILS', '').split(',') if e.strip()
]

# Currency settings
CURRENCY = os.getenv('CURRENCY', 'NGN')
CURRENCY_SYMBOL = os.getenv('CURRENCY_SYMBOL', '₦')

# Security Settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
X_FRAME_OPTIONS = 'DENY'  # Prevent clickjacking
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# Additional Security Headers
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'
SECURE_CROSS_ORIGIN_EMBEDDER_POLICY = 'require-corp'

# Cookie / transport security. Only enforced outside DEBUG so local http
# development keeps working.
# PythonAnywhere (and most PaaS) terminate TLS at a proxy and forward the
# original scheme in X-Forwarded-Proto. Django needs this to know the request
# was really HTTPS — without it, SECURE_SSL_REDIRECT causes a redirect loop.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Shared secret proving a request really came from our own frontend proxy, so
# the visitor IP it forwards in X-Client-IP can be trusted (see
# RealClientIPMiddleware). MUST be the same value on the frontend (Vercel) and
# here. Leave empty to disable IP recovery — rate limits then fall back to the
# proxy's IP, which throttles the whole site as one client.
PROXY_SHARED_SECRET = os.getenv('PROXY_SHARED_SECRET', '')

SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = False  # JS must read the CSRF token to send it back
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# Kept env-toggleable: if the proxy ever stops sending X-Forwarded-Proto this
# is the switch to flip before the site becomes unreachable.
SECURE_SSL_REDIRECT = os.getenv(
    'SECURE_SSL_REDIRECT', 'False' if DEBUG else 'True'
) == 'True'

# Celery Configuration
# Check if Redis is available for Celery
REDIS_AVAILABLE_FOR_CELERY = False
try:
    import redis
    r = redis.Redis(host='127.0.0.1', port=6379, db=0)
    r.ping()
    REDIS_AVAILABLE_FOR_CELERY = True
    print("Redis available for Celery")
except:
    print("Redis not available for Celery - using database broker")

if REDIS_AVAILABLE_FOR_CELERY:
    CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0')
    CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'
else:
    # Use database as broker when Redis is not available
    CELERY_BROKER_URL = 'django-db'
    CELERY_RESULT_BACKEND = 'django-db'

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_ENABLE_UTC = True

# Celery task settings
CELERY_TASK_SOFT_TIME_LIMIT = 300  # 5 minutes
CELERY_TASK_TIME_LIMIT = 600       # 10 minutes
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000

# Celery beat settings
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# File Upload Settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
FILE_UPLOAD_PERMISSIONS = 0o644

# Content Security Policy (CSP) - New format for django-csp 4.0+
CONTENT_SECURITY_POLICY = {
    'DIRECTIVES': {
        'default-src': ("'self'",),
        'style-src': ("'self'", "'unsafe-inline'", "https://fonts.googleapis.com"),
        'script-src': ("'self'", "'unsafe-inline'", "https://js.paystack.co"),
        'img-src': ("'self'", "data:", "https:", "blob:"),
        'font-src': ("'self'", "https://fonts.gstatic.com"),
        'connect-src': ("'self'", "https://api.paystack.co"),
        'frame-src': ("'self'", "https://checkout.paystack.com"),
        'object-src': ("'none'",),
        'base-uri': ("'self'",),
        'form-action': ("'self'", "https://checkout.paystack.com"),
    }
}

# Redis Caching Configuration
# Check if Redis is available and running
REDIS_AVAILABLE = False
try:
    import redis
    r = redis.Redis(host='127.0.0.1', port=6379, db=1)
    r.ping()  # Test connection
    REDIS_AVAILABLE = True
    print("Redis is running - using Redis cache")
except:
    print("Redis not available - using local memory cache")

if REDIS_AVAILABLE:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/1'),
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'CONNECTION_POOL_KWARGS': {
                    'max_connections': 50,
                    'retry_on_timeout': True,
                },
            },
            'KEY_PREFIX': 'darra_app',
            'TIMEOUT': 300,  # 5 minutes default timeout
        }
    }
else:
    # Fallback to local memory cache if Redis is not available
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
            'OPTIONS': {
                'MAX_ENTRIES': 1000,
                'CULL_FREQUENCY': 3,
            },
            'TIMEOUT': 300,
        }
    }

# Session caching
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'
SESSION_COOKIE_AGE = 3600  # 1 hour

# Cache configuration for different data types
CACHE_TIMEOUTS = {
    'user_data': 300,      # 5 minutes
    'product_list': 600,   # 10 minutes
    'product_detail': 1800, # 30 minutes
    'payment_data': 60,    # 1 minute
    'notification': 300,   # 5 minutes
}

# Performance monitoring
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'django_performance.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django.db.backends': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'django.cache': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'performance': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}
