# Generated by Django 5.2.4 on 2025-07-14 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_type', models.CharField(choices=[('pdf', 'PDF'), ('mp3', 'MP3'), ('docx', 'DOCX'), ('png', 'PNG'), ('zip', 'ZIP'), ('video', 'Video'), ('event', 'Event')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='products/files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('ticket_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
