# Generated by Django 5.2.5 on 2025-08-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_ticketcategory_product_ticket_category_tickettier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_html',
            field=models.TextField(blank=True),
        ),
    ]
