# Generated by Django 5.2.9 on 2026-07-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_switch_to_local_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='event_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='speakers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='venue_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
