# Generated by Django 5.2.9 on 2026-07-22 20:29

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_event_end_date_product_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file',
            field=models.FileField(blank=True, null=True, storage=products.models.private_product_storage, upload_to='products/files/'),
        ),
    ]
