# Generated by Django 5.2.9 on 2026-07-23 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickettier',
            options={'ordering': ['price'], 'verbose_name': 'Ticket category', 'verbose_name_plural': 'Ticket categories'},
        ),
        migrations.AlterUniqueTogether(
            name='tickettier',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tickettier',
            name='color',
            field=models.CharField(default='#5465FF', help_text='Badge colour in the UI.', max_length=7),
        ),
        migrations.AlterField(
            model_name='tickettier',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Legacy. New ticket types are named directly by the seller.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiers', to='products.ticketcategory'),
        ),
    ]
