# Generated by Django 5.2.5 on 2025-09-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventticket',
            name='pdf_ticket_cloudinary_id',
        ),
        migrations.RemoveField(
            model_name='eventticket',
            name='qr_code_cloudinary_id',
        ),
        migrations.AddField(
            model_name='eventticket',
            name='pdf_ticket_file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='eventticket',
            name='qr_code_file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='eventticket',
            name='pdf_ticket',
            field=models.FileField(blank=True, null=True, upload_to='tickets/pdf/'),
        ),
        migrations.AlterField(
            model_name='eventticket',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='tickets/qr_codes/'),
        ),
    ]
