# Generated by Django 5.2.5 on 2025-08-30 23:40

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventticket_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventticket',
            name='pdf_ticket',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='tickets/pdf/'),
        ),
        migrations.AddField(
            model_name='eventticket',
            name='pdf_ticket_cloudinary_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventticket',
            name='qr_code_cloudinary_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventticket',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='tickets/qr_codes/'),
        ),
    ]
