# Generated by Django 5.2.5 on 2025-09-06 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_fasteventticket'),
        ('events', '0002_remove_eventticket_pdf_ticket_cloudinary_id_and_more'),
    ]

    operations = [
    ]
