# Generated by Django 5.2.5 on 2025-08-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userlibrary',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userlibrary',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
