# Generated by Django 5.2.5 on 2025-08-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_userlibrary_product_alter_userlibrary_purchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='flutterwave_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_provider',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave')], default='paystack', max_length=20),
        ),
    ]
