# Generated by Django 5.2.5 on 2025-08-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_flutterwave_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutrequest',
            name='flutterwave_transfer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
