# Generated by Django 5.2.5 on 2025-08-28 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payoutrequest_flutterwave_transfer_id'),
        ('products', '0003_ticketcategory_product_ticket_category_tickettier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='selected_ticket_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='products.tickettier'),
        ),
    ]
