# Generated by Django 5.2.17 on 2026-08-26 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_purchase_selected_ticket_tier"),
        ("products", "0015_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchases",
                to="products.coupon",
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
