# Generated by Django 5.2.4 on 2025-07-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='close_time',
            field=models.CharField(blank=True, default='18:00', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='open_time',
            field=models.CharField(blank=True, default='09:00', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='store_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='brand_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='brand_slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
